site_name: Hover
site_description: "Hover and label data rapidly."
site_url: "https://phurwicz.github.io/hover"
repo_url: "https://github.com/phurwicz/hover.git"
repo_name: "phurwicz/hover"

theme:
    name: material
    icon:
      logo: material/alpha-h-box
    favicon: images/favicon.png
    font:
      text: Roboto
      code: Roboto Mono
    features:
      - navigation.expand
      - navigation.tabs
      - search.suggest
      - toc.integrate
    palette:
      # Palette toggle for light mode
      - scheme: default
        toggle:
          icon: material/weather-night
          name: Switch to dark mode

      # Palette toggle for dark mode
      - scheme: slate
        toggle:
          icon: material/weather-sunny
          name: Switch to light mode

nav:
    - Home: 'index.md'
    - 'Basics':
        - 'Quickstart': 'pages/tutorial/t0-quickstart.md'
        - 'Using Recipes': 'pages/tutorial/t1-active-learning.md'
        - 'Handling Images': 'pages/guides/g0-datatype-image.md'
        - 'Handling Audio': 'pages/guides/g1-datatype-audio.md'
    - 'Mechanisms':
        - 'Managing Data': 'pages/tutorial/t3-dataset-population-selection.md'
        - 'Applying Labels': 'pages/tutorial/t4-annotator-dataset-interaction.md'
    - 'Options':
        - 'Host Options': 'pages/tutorial/t2-bokeh-app.md'
        - 'Custom Config': 'pages/guides/g2-hover-config.md'
    - 'Powerful Tricks':
        - 'Finder & Selection Filter': 'pages/tutorial/t5-finder-filter.md'
        - 'Soft Label & Joint Filters': 'pages/tutorial/t6-softlabel-joint-filter.md'
        - 'Custom Labeling Functions': 'pages/tutorial/t7-snorkel-improvise-rules.md'
    #    - 'Data Type: Multimodal': 'pages/topics/datatype-multimodal.md'
        #- 'Why Hover': 'pages/topics/what-hover-is.md'
        #- 'Customized Usage':
        #    - 'API Levels': 'pages/topics/api-levels.md' # discuss the interaction between recipe / dataset / explorer
        #    - 'Custom Recipe': 'pages/topics/custom-recipe.md' # discuss the caveats when making a recipe
        #    - 'Subclassing Dataset': 'pages/topics/custom-dataset.md' # discuss the caveats when subclassing a SupervisableDataset
        #    - 'Subclassing Explorer': 'pages/topics/custom-explorer.md' # discuss the caveats when subclassing a BokehBaseExplorer
    - 'API Reference':
        - 'hover.recipes': 'pages/reference/recipes.md'
        - 'hover.core':
            - '.dataset': 'pages/reference/core-dataset.md'
            - '.explorer':
                - '.base': 'pages/reference/core-explorer-base.md'
                - '.feature': 'pages/reference/core-explorer-feature.md'
                - '.functionality': 'pages/reference/core-explorer-functionality.md'
                - '.specialization': 'pages/reference/core-explorer-specialization.md'
            - '.neural': 'pages/reference/core-neural.md'
            - '.representation': 'pages/reference/core-representation.md'
        - 'hover.utils':
            - '.bokeh_helper': 'pages/reference/utils-bokeh_helper.md'
            - '.snorkel_helper': 'pages/reference/utils-snorkel_helper.md'

markdown_extensions:
  - admonition
  - def_list
  - markdown_include.include
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - macros
  - search:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_heading: true
            show_source: true
      watch:
        - hover
  - i18n:
      default_language: en
      languages:
        en: English
        # fr: français
        zh: 简体中文
      nav_translations:
        zh:
          Home: 主页
          Basics: 基础使用
          Mechanisms: 理解机制
          Options: 自定配置
          Powerful Tricks: 高级技巧
          API Reference: API 指南

extra:
  version:
    provider: mike
  analytics:
    provider: google
    property: G-M3WR5YEJ33
